### PR TITLE
Windows Support

### LINKED ISSUE #21: Windows Support
Hello @boydm !

In the past I wrote an article on making a snake game with Scenic and recently I've received [some feedback](https://medium.com/@habamax/non-windows-i-suppose-50a5167724bc) from a Windows user who'd had trouble getting the setup working. Even though I don't use Windows in my main development environment I really wanted to try and build it there so I could hopefully reply with instructions, but as I began to experiment I realized there were multiple small amendments to be made, mostly due to a handful of convenient libraries and/or features not being available there.

With the growth of the Linux Subsystem in Windows it's [not entirely impossible](https://www.mdsebald.org/elixir-scenic-ui-library-test-drive/) to get Scenic up and running in a Windows 10 system, but since there aren't many dependencies tying it up, it should be perfectly possible to have an easier way for the Windows users to get started. The earlier this is tackled, the less daunting of a task it should be, so why not now? :)

-----

Here's an outline on the current incompatibilities and missing pieces: (this list may be incomplete)

* [x] A nmake-compatible `Makefile.win` file. `pkg-config` won't be as reliable in Windows unfortunately, so we might have to vendor in OpenGL, GLFW and GLEW dlls in priv?
* [x] A replacement for `poll.h`. It seems to be used only in `main.c` to check whether STDIN was closed in `isCallerDown()`. Not extremely sure on a good candidate to replace this one yet. 
* [x] A replacement for `sys/time.h`. Looks like it's used in `comms.c` as its `timeval` struct and `gettimeofday()` function. Some kind folks at StackOverflow have provided [an implementation](https://stackoverflow.com/a/26085827) of `gettimeofday()` that could be handy. The struct shouldn't be too complicated either.
* [x] A replacement for `sys/select.h`. It's also in `comms.c`, stuff like `fd_set`  and `select()` are used to look for stdin data when it becomes available. I've yet to delve deeper into this one but it looks like some nominal replacements exist in `WinSock2.h` although they might not be suited to interact with the stdin, only actual sockets.
* [x] A replacement for `__attribute__ ((__packed__))`. Used extensively in `comms.c` and `render_script.c`. Luckily this one shouldn't require much work either, thanks to [these StackOverflow answers](https://stackoverflow.com/questions/1537964/visual-c-equivalent-of-gccs-attribute-packed).
* [x] A replacement for `unistd.h`. With some luck, MSVC's `io.h` might handle this one.
* [x] Explicit type casts when adding to void pointers. It's everywhere in `render_script.c`, likely so that the rendering procedure can step over to the next command. Also appears once in `tx.c`. [GCC allows this by considering the size as 1](http://gcc.gnu.org/onlinedocs/gcc-4.8.0/gcc/Pointer-Arith.html), but it's not allowed elsewhere. We can get away by casting to `char *` before adding up and casting back to `void *` afterwards. 

-----

The more involved ones seem to be regarding the reading/polling of the STDIN. (advice on that would be welcome!)
Please let me know what you think of this. Are these changes viable and compatible with the evolution of the library?

### PR DESCRIPTION
**Pull request by gVirtu**
This PR closes #21 .

## Overview

 * Added `Makefile.win`.
 * Added installation instructions in `README.md`.
 * Separate platform-specific logic: added Windows implementations for `isCallerDown`, `read_exact`, `read_msg_length` and `write_exact`.
    - These are located in a new file named `windows_comms.c`.
    - Former implementations were placed in `unix_comms.c`.
    - The `swap_little_endian_uint` function was created to avoid having to expose the `f_little_endian` variable to the new files.
    - [Made sure the `comms.h` was always included before GLFW to prevent an ugly warning](https://stackoverflow.com/questions/3927810/how-to-prevent-macro-redefinition).
  * Added a `PACK` macro as MSVC does not support the `__attribute__((packed))` syntax.
  * [Added a `gettimeofday` implementation](https://stackoverflow.com/a/26085827).
  * All void pointer operations are now explicitly casted to char pointer, then casted back.
  * Append the `.exe` extension to the Port filename only on Windows

## Tested on
 * [x] Windows 10 (x64)
 * [x] Ubuntu 16.04

Looking to having this list expanded!

### CODE REVIEW

**Comment by boydm** [comment]
I'll be digging into this shortly. Thank you for the hard work!

**Comment by boydm** [comment]
How are you feeling about this so far? What is your confidence that it is working?
I'm still traveling for a bit more, but I'm thinking through what needs to be done to merge it in.

**Comment by gVirtu** [comment]
I believe the changes introduced are low level enough that it'll either _mostly work_ or _not work at all_ on a given system. The platforms in the 'Tested On' list were the ones I could successfully (and visibly) run the integration test suite, in addition to exploring the features in `scenic_new`'s example app, though with no formal process.

That said, even though it seems to be working alright, unfortunately I can't speak for platforms such as MacOS or Nerves Linux yet. Once the major target platforms are reasonably covered, it might also be a good idea to have the community help detect edge cases by including this in an unstable/beta release first.

**Comment by gVirtu** [comment]
@boydm I'm still open to further developing on this :)
Let me know what you think we still need in order to get this to rock solid.
Thanks!

**Comment by boydm** [comment]
(finally) Ready to pull this in.

**Review by boydm — APPROVED** [review]

**Comment by boydm** [comment]
Thank you!

**Pull request merged**
